// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xoA7omHX1aucC3LFX3rgWp
// Component: TPNiGfUjvdq1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Container from "../../Container"; // plasmic-import: yjb-qhVvhQe-/component
import Button from "../../Button"; // plasmic-import: 3AR6h0473ToW/component

import { useScreenVariants as useScreenVariantsohEUf6Jd0EV8 } from "../core/PlasmicGlobalVariant__Screen"; // plasmic-import: OhEUf6Jd0eV8/globalVariant
import { ThemeValue, useTheme } from "../core/PlasmicGlobalVariant__Theme"; // plasmic-import: yBTVTgAz2Co9/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_core_css from "../core/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_semantic_css from "../semantic/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import plasmic_desktop_ui_theme_css from "../desktop_ui_theme/plasmic.module.css"; // plasmic-import: 6eqm1KNiFrAWEs21Xh4t1D/projectcss
import plasmic_advance_card_css from "../advance_card/plasmic.module.css"; // plasmic-import: 71RGmKESGHwX1FQiVTH6Ch/projectcss
import plasmic_form_input_css from "../form_input/plasmic.module.css"; // plasmic-import: teUZ7d8BEHskoXuvEf1pBj/projectcss
import plasmic_icon_css from "../icon/plasmic.module.css"; // plasmic-import: nVTL6BvP7Knk1RSNkBbJCm/projectcss
import plasmic_statistic_css from "../statistic/plasmic.module.css"; // plasmic-import: tq1m84LuCppLaXTJBWMK12/projectcss
import plasmic_avatar_css from "../avatar/plasmic.module.css"; // plasmic-import: wjwfXMtbnYisAPU4bK5cC5/projectcss
import plasmic_button_css from "../button/plasmic.module.css"; // plasmic-import: 4JFyEcvXaxQ6TZ3SJQYzp6/projectcss
import plasmic_image_css from "../image/plasmic.module.css"; // plasmic-import: d4FLWyib3U2TEbmJ38D5i3/projectcss
import plasmic_container_css from "../container/plasmic.module.css"; // plasmic-import: d9PrY1SRs2wAiwFXTkwPXt/projectcss
import plasmic_switch_css from "../switch/plasmic.module.css"; // plasmic-import: i4n9AbVD4xq7VvHzvrVDh9/projectcss
import plasmic_label_css from "../badge/plasmic.module.css"; // plasmic-import: 6PoNur73nfoJqbzNtkNpAX/projectcss
import plasmic_menu_item_css from "../menu_item/plasmic.module.css"; // plasmic-import: 2ejMdvJDoJWjwd6DCNSCHJ/projectcss
import plasmic_separator_css from "../separator/plasmic.module.css"; // plasmic-import: mGt6E9beS9xM1LmsApto9L/projectcss
import plasmic_form_checkbox_css from "../form_checkbox/plasmic.module.css"; // plasmic-import: bEVQSMSYHutfoPgsCgDaki/projectcss
import plasmic_form_select_css from "../form_select/plasmic.module.css"; // plasmic-import: ivrmEdvdUKbShkHq3Wnmy4/projectcss
import plasmic_list_item_css from "../list_item/plasmic.module.css"; // plasmic-import: fKizj5juSSuZK31zh3BBJE/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: xoA7omHX1aucC3LFX3rgWp/projectcss
import sty from "./PlasmicTestimonialSectionTestimonials.module.css"; // plasmic-import: TPNiGfUjvdq1/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 1l0k0f8No_g4/icon
import FaArrowRightSvgIcon from "../icons/icons/PlasmicIcon__FaArrowRightsvg"; // plasmic-import: laMKK4I5P9un/icon

createPlasmicElementProxy;

export type PlasmicTestimonialSectionTestimonials__VariantMembers = {};
export type PlasmicTestimonialSectionTestimonials__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicTestimonialSectionTestimonials__VariantsArgs;
export const PlasmicTestimonialSectionTestimonials__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTestimonialSectionTestimonials__ArgsType = {};
type ArgPropType = keyof PlasmicTestimonialSectionTestimonials__ArgsType;
export const PlasmicTestimonialSectionTestimonials__ArgProps =
  new Array<ArgPropType>();

export type PlasmicTestimonialSectionTestimonials__OverridesType = {
  testimonialsContainer?: Flex__<typeof Container>;
  testimonialSection?: Flex__<"div">;
  testimonialArea?: Flex__<"div">;
  h2?: Flex__<"h2">;
  button?: Flex__<typeof Button>;
  testimonialGroup?: Flex__<"div">;
  testimonialItemWrapper?: Flex__<"div">;
  testimonialItem?: Flex__<"div">;
};

export interface DefaultTestimonialSectionTestimonialsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTestimonialSectionTestimonials__RenderFunc(props: {
  variants: PlasmicTestimonialSectionTestimonials__VariantsArgs;
  args: PlasmicTestimonialSectionTestimonials__ArgsType;
  overrides: PlasmicTestimonialSectionTestimonials__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsohEUf6Jd0EV8(),
    theme: useTheme()
  });

  return (
    <Container
      data-plasmic-name={"testimonialsContainer"}
      data-plasmic-override={overrides.testimonialsContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.testimonialsContainer)}
      containerLayout={["heightHug"]}
      containerSlot={
        <div
          data-plasmic-name={"testimonialSection"}
          data-plasmic-override={overrides.testimonialSection}
          className={classNames(projectcss.all, sty.testimonialSection)}
        >
          <div
            data-plasmic-name={"testimonialArea"}
            data-plasmic-override={overrides.testimonialArea}
            className={classNames(projectcss.all, sty.testimonialArea)}
          >
            <h2
              data-plasmic-name={"h2"}
              data-plasmic-override={overrides.h2}
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2
              )}
            >
              {"Lorem Ipsum"}
            </h2>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mrS0X
              )}
            >
              {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
              }
            </div>
            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              background={"primary"}
              className={classNames("__wab_instance", sty.button)}
              endIcon={
                <IconIcon
                  className={classNames(projectcss.all, sty.svg__iMpa4)}
                  role={"img"}
                />
              }
              startIcon={
                <svg
                  className={classNames(projectcss.all, sty.svg___2ROmi)}
                  role={"img"}
                />
              }
              submitsForm={true}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__e4Oyi
                )}
              >
                {"Lorem ipsum"}
              </div>
            </Button>
            <Stack__
              as={"div"}
              data-plasmic-name={"testimonialGroup"}
              data-plasmic-override={overrides.testimonialGroup}
              hasGap={true}
              className={classNames(projectcss.all, sty.testimonialGroup)}
            >
              <div
                data-plasmic-name={"testimonialItemWrapper"}
                data-plasmic-override={overrides.testimonialItemWrapper}
                className={classNames(
                  projectcss.all,
                  sty.testimonialItemWrapper
                )}
              >
                <div
                  data-plasmic-name={"testimonialItem"}
                  data-plasmic-override={overrides.testimonialItem}
                  className={classNames(projectcss.all, sty.testimonialItem)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__tvLwh)}
                    displayHeight={"auto"}
                    displayMaxHeight={"64px"}
                    displayMaxWidth={"64px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/desktop_starter/images/image27.png",
                      fullWidth: 128,
                      fullHeight: 128,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d82Ft
                    )}
                  >
                    {"Jocylne Kujo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__syMPq
                    )}
                  >
                    {"Founder Flappin"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aghKp
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__sPcn)}>
                <div className={classNames(projectcss.all, sty.freeBox__ssss)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pzUS)}
                    displayHeight={"auto"}
                    displayMaxHeight={"64px"}
                    displayMaxWidth={"64px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/desktop_starter/images/image27.png",
                      fullWidth: 128,
                      fullHeight: 128,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2X8L6
                    )}
                  >
                    {"Jocylne Kujo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b1NhF
                    )}
                  >
                    {"Founder Flappin"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mOkA
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rTwxq)}>
                <div className={classNames(projectcss.all, sty.freeBox__gs6Dw)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9XyeZ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"64px"}
                    displayMaxWidth={"64px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/desktop_starter/images/image27.png",
                      fullWidth: 128,
                      fullHeight: 128,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oXJm
                    )}
                  >
                    {"Jocylne Kujo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mAeYh
                    )}
                  >
                    {"Founder Flappin"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7J3Qa
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__x6Zqf)}>
                <div className={classNames(projectcss.all, sty.freeBox__qJ5Z0)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dieSd)}
                    displayHeight={"auto"}
                    displayMaxHeight={"64px"}
                    displayMaxWidth={"64px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/desktop_starter/images/image27.png",
                      fullWidth: 128,
                      fullHeight: 128,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fTIh
                    )}
                  >
                    {"Jocylne Kujo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wBro8
                    )}
                  >
                    {"Founder Flappin"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fzd7O
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rBne9)}>
                <div className={classNames(projectcss.all, sty.freeBox__xhOSq)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pSbaA)}
                    displayHeight={"auto"}
                    displayMaxHeight={"64px"}
                    displayMaxWidth={"64px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/desktop_starter/images/image27.png",
                      fullWidth: 128,
                      fullHeight: 128,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7Zmda
                    )}
                  >
                    {"Jocylne Kujo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__swWwF
                    )}
                  >
                    {"Founder Flappin"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dLNnd
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___55Em4)}>
                <div className={classNames(projectcss.all, sty.freeBox__jEa2W)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wvx37)}
                    displayHeight={"auto"}
                    displayMaxHeight={"64px"}
                    displayMaxWidth={"64px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/desktop_starter/images/image27.png",
                      fullWidth: 128,
                      fullHeight: 128,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4JmRu
                    )}
                  >
                    {"Jocylne Kujo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__igWk
                    )}
                  >
                    {"Founder Flappin"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7EVlc
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    }
                  </div>
                </div>
              </div>
            </Stack__>
          </div>
        </div>
      }
      layer01={["backgroundUniversal"]}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  testimonialsContainer: [
    "testimonialsContainer",
    "testimonialSection",
    "testimonialArea",
    "h2",
    "button",
    "testimonialGroup",
    "testimonialItemWrapper",
    "testimonialItem"
  ],
  testimonialSection: [
    "testimonialSection",
    "testimonialArea",
    "h2",
    "button",
    "testimonialGroup",
    "testimonialItemWrapper",
    "testimonialItem"
  ],
  testimonialArea: [
    "testimonialArea",
    "h2",
    "button",
    "testimonialGroup",
    "testimonialItemWrapper",
    "testimonialItem"
  ],
  h2: ["h2"],
  button: ["button"],
  testimonialGroup: [
    "testimonialGroup",
    "testimonialItemWrapper",
    "testimonialItem"
  ],
  testimonialItemWrapper: ["testimonialItemWrapper", "testimonialItem"],
  testimonialItem: ["testimonialItem"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  testimonialsContainer: typeof Container;
  testimonialSection: "div";
  testimonialArea: "div";
  h2: "h2";
  button: typeof Button;
  testimonialGroup: "div";
  testimonialItemWrapper: "div";
  testimonialItem: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestimonialSectionTestimonials__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestimonialSectionTestimonials__VariantsArgs;
    args?: PlasmicTestimonialSectionTestimonials__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicTestimonialSectionTestimonials__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      PlasmicTestimonialSectionTestimonials__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestimonialSectionTestimonials__ArgProps,
          internalVariantPropNames:
            PlasmicTestimonialSectionTestimonials__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestimonialSectionTestimonials__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "testimonialsContainer") {
    func.displayName = "PlasmicTestimonialSectionTestimonials";
  } else {
    func.displayName = `PlasmicTestimonialSectionTestimonials.${nodeName}`;
  }
  return func;
}

export const PlasmicTestimonialSectionTestimonials = Object.assign(
  // Top-level PlasmicTestimonialSectionTestimonials renders the root element
  makeNodeComponent("testimonialsContainer"),
  {
    // Helper components rendering sub-elements
    testimonialSection: makeNodeComponent("testimonialSection"),
    testimonialArea: makeNodeComponent("testimonialArea"),
    h2: makeNodeComponent("h2"),
    button: makeNodeComponent("button"),
    testimonialGroup: makeNodeComponent("testimonialGroup"),
    testimonialItemWrapper: makeNodeComponent("testimonialItemWrapper"),
    testimonialItem: makeNodeComponent("testimonialItem"),

    // Metadata about props expected for PlasmicTestimonialSectionTestimonials
    internalVariantProps: PlasmicTestimonialSectionTestimonials__VariantProps,
    internalArgProps: PlasmicTestimonialSectionTestimonials__ArgProps
  }
);

export default PlasmicTestimonialSectionTestimonials;
/* prettier-ignore-end */
